# Generated by Django 4.0.2 on 2022-02-17 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='receipt_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 7, 20, 47, 986560)),
        ),
    ]
