# Generated by Django 4.0.2 on 2022-02-17 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_alter_donor_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='receipt_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 7, 23, 14, 263414)),
        ),
    ]
